apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: grafana-datasources
    files:
      - datasources.yaml=../../../grafana/provisioning/datasources/datasources.yaml
  - name: grafana-dashboards-config
    files:
      - dashboards.yaml=../../../grafana/provisioning/dashboards/dashboards.yaml
  - name: grafana-dashboards-ac
    options:
      labels:
        grafana_dashboard: "1"
    files:
      - ac-logs.json=../../../grafana/dashboards/ac-logs.json
      - ac-overview.json=../../../grafana/dashboards/ac-overview.json
      - ac-slos.json=../../../grafana/dashboards/ac-slos.json
  - name: grafana-dashboards-gc
    options:
      labels:
        grafana_dashboard: "1"
    files:
      - gc-logs.json=../../../grafana/dashboards/gc-logs.json
      - gc-overview.json=../../../grafana/dashboards/gc-overview.json
      - gc-slos.json=../../../grafana/dashboards/gc-slos.json
  - name: grafana-dashboards-mc
    options:
      labels:
        grafana_dashboard: "1"
    files:
      - mc-logs.json=../../../grafana/dashboards/mc-logs.json
      - mc-overview.json=../../../grafana/dashboards/mc-overview.json
      - mc-slos.json=../../../grafana/dashboards/mc-slos.json
  - name: grafana-dashboards-errors
    options:
      labels:
        grafana_dashboard: "1"
    files:
      - errors-overview.json=../../../grafana/dashboards/errors-overview.json
