apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gc-service
  namespace: dark-tower
  labels:
    app: gc-service
    component: gateway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: gc-service
      component: gateway
