# ServiceMonitor for Prometheus metrics scraping
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gc-service
  namespace: dark-tower
  labels:
    app: gc-service
    component: gateway
spec:
  selector:
    matchLabels:
      app: gc-service
      component: gateway
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    scheme: http
