apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ac-service
  namespace: dark-tower
  labels:
    app: ac-service
    component: auth
spec:
  podSelector:
    matchLabels:
      app: ac-service
      component: auth
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow ingress from Global Controller (for JWT validation and token acquisition)
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: dark-tower
      podSelector:
        matchLabels:
          app: gc-service
    ports:
    - protocol: TCP
      port: 8082
  # Allow ingress from Meeting Controller (for token acquisition)
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: dark-tower
      podSelector:
        matchLabels:
          app: mc-service
    ports:
    - protocol: TCP
      port: 8082
  # Allow ingress from Prometheus for metrics scraping
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: dark-tower-observability
      podSelector:
        matchLabels:
          app: prometheus
    ports:
    - protocol: TCP
      port: 8082
  egress:
  # Allow egress to PostgreSQL
  - to:
    - podSelector:
        matchLabels:
          app: postgres
    ports:
    - protocol: TCP
      port: 5432
  # Allow DNS resolution
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
