apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ac-service
  namespace: dark-tower
  labels:
    app: ac-service
    component: auth
spec:
  serviceName: ac-service
  replicas: 2
  selector:
    matchLabels:
      app: ac-service
      component: auth
  template:
    metadata:
      labels:
        app: ac-service
        component: auth
    spec:
      terminationGracePeriodSeconds: 35
      securityContext:
        runAsNonRoot: true
        # Match distroless nonroot user (uid 65532)
        runAsUser: 65532
        fsGroup: 65532
      containers:
      - name: ac-service
        image: ac-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: https
          containerPort: 8082
          protocol: TCP
        env:
        - name: AC_CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: ac-service-config
              key: AC_CLUSTER_NAME
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ac-service-secrets
              key: DATABASE_URL
        - name: AC_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: ac-service-secrets
              key: AC_MASTER_KEY
        - name: RUST_LOG
          value: "info,ac_service=debug"
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 2Gi
        securityContext:
          runAsNonRoot: true
          runAsUser: 65532
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8082
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
