apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: meeting-controller
  namespace: dark-tower
  labels:
    app: meeting-controller
    component: signaling
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: meeting-controller
      component: signaling
