apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: dark-tower
  labels:
    app: redis
    component: cache
type: Opaque
stringData:
  # Development password - override in production via external-secrets or sealed-secrets
  REDIS_PASSWORD: "dev-redis-password-change-in-prod"
