apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: dark-tower
  labels:
    app: redis
    component: cache
type: Opaque
stringData:
  # Development password - override in production via external-secrets or sealed-secrets
  # Matches inline Redis in setup.sh
  REDIS_PASSWORD: "dev_password_change_in_production"
