//! P1 Tests: Join Flow (AC → GC → MC End-to-End)
//!
//! End-to-end tests validating the full meeting join path across all three services.
//!
//! # Prerequisites
//!
//! - Kind cluster with AC, GC, and MC deployed
//! - Port-forwards active: AC (8082), GC (8080), MC WebTransport (4433)
//! - Test data seeded: `devtest` organization in database
//! - AC_JWKS_URL configured on GC and MC for token validation
//!
//! # TLS Note
//!
//! MC WebTransport uses self-signed dev certs generated by `scripts/generate-dev-certs.sh`.
//! The dev CA is at `infra/docker/certs/ca.crt`. MC tests use
//! `with_no_cert_validation()` (matching the pattern in `mc-service/tests/join_tests.rs`)
//! because the dev CA cert is generated at Kind setup time and not committed to the repo.

#![cfg(feature = "flows")]

use bytes::{BufMut, BytesMut};
use env_tests::cluster::ClusterConnection;
use env_tests::fixtures::auth_client::{TokenRequest, UserRegistrationRequest};
use env_tests::fixtures::gc_client::{CreateMeetingRequest, GcClient, GcClientError};
use env_tests::fixtures::AuthClient;
use prost::Message;
use proto_gen::signaling::{
    client_message, server_message, ClientMessage, JoinRequest, ServerMessage,
};
use std::time::Duration;
use tokio::sync::OnceCell;

// ============================================================================
// Test Infrastructure
// ============================================================================

/// Shared cluster connection (initialized once, reused across all tests).
static CLUSTER: OnceCell<ClusterConnection> = OnceCell::const_new();

/// Shared test user token (reduces registration count within rate limit budget).
/// Tests that only need a valid user JWT reuse this instead of registering their own.
static SHARED_USER: OnceCell<(String, String)> = OnceCell::const_new();

/// Helper to get a cluster connection, verifying AC + GC are available.
///
/// Used by all tests. Does NOT check MC availability — MC tests will fail
/// with a clear error if MC is not reachable.
async fn cluster() -> &'static ClusterConnection {
    CLUSTER
        .get_or_init(|| async {
            let cluster = ClusterConnection::new()
                .await
                .expect("Failed to connect to cluster - ensure port-forwards are running");
            cluster
                .check_ac_health()
                .await
                .expect("AC service must be running for join flow tests");
            cluster
                .check_gc_health()
                .await
                .expect("GC service must be running for join flow tests");
            cluster
        })
        .await
}

/// Get a shared test user token for GC-level tests.
///
/// Returns (access_token, display_name). Registers the user once via AC;
/// subsequent calls return the cached token. This keeps GC-level registration
/// count to 1 instead of 5, staying well within AC's 5/hour rate limit.
async fn shared_user(cluster: &ClusterConnection) -> &'static (String, String) {
    SHARED_USER
        .get_or_init(|| async {
            let auth_client = AuthClient::new(&cluster.ac_base_url);
            register_test_user(&auth_client, "Join Flow Shared User").await
        })
        .await
}

/// Register a test user via AC and return the user JWT access token and display name.
async fn register_test_user(auth_client: &AuthClient, display_name: &str) -> (String, String) {
    let request = UserRegistrationRequest::unique(display_name);
    let display = request.display_name.clone();
    let response = auth_client
        .register_user(&request)
        .await
        .expect("AC should register test user");
    (response.access_token, display)
}

/// Connect a wtransport client to the MC WebTransport endpoint.
///
/// Uses `with_no_cert_validation()` for Kind's self-signed dev certs.
/// Dev CA is generated by `scripts/generate-dev-certs.sh` at Kind setup time
/// and is not available in CI. This matches `mc-service/tests/join_tests.rs`.
async fn connect_mc(url: &str) -> wtransport::Connection {
    let client_config = wtransport::ClientConfig::builder()
        .with_bind_default()
        .with_no_cert_validation()
        .build();

    let client = wtransport::Endpoint::client(client_config).expect("create WebTransport client");
    client
        .connect(url)
        .await
        .expect("connect to MC WebTransport")
}

/// Encode a `ClientMessage` as a length-prefixed frame (4-byte BE length + protobuf).
///
/// Wire format matches MC's `connection.rs` framing protocol.
fn encode_framed(msg: &ClientMessage) -> Vec<u8> {
    let encoded = msg.encode_to_vec();
    let len = encoded.len() as u32;
    let mut frame = BytesMut::with_capacity(4 + encoded.len());
    frame.put_u32(len);
    frame.put_slice(&encoded);
    frame.to_vec()
}

/// Read a length-prefixed `ServerMessage` from a recv stream.
///
/// Returns `None` if the stream is closed or the message is malformed.
async fn read_server_message(recv: &mut wtransport::stream::RecvStream) -> Option<ServerMessage> {
    let mut len_buf = [0u8; 4];
    if recv.read_exact(&mut len_buf).await.is_err() {
        return None;
    }

    let msg_len = u32::from_be_bytes(len_buf) as usize;
    if msg_len == 0 || msg_len > 65536 {
        return None;
    }

    let mut buf = vec![0u8; msg_len];
    if recv.read_exact(&mut buf).await.is_err() {
        return None;
    }

    ServerMessage::decode(buf.as_slice()).ok()
}

/// Send a JoinRequest over a WebTransport bidi stream and read the response.
///
/// Opens a new bidi stream on the connection, sends the framed JoinRequest,
/// and reads the ServerMessage response with a timeout.
async fn send_join_and_read_response(
    conn: &wtransport::Connection,
    meeting_id: &str,
    join_token: &str,
    participant_name: &str,
) -> ServerMessage {
    let (mut send, mut recv) = conn
        .open_bi()
        .await
        .expect("open bi stream")
        .await
        .expect("bi stream ready");

    let client_msg = ClientMessage {
        message: Some(client_message::Message::JoinRequest(JoinRequest {
            meeting_id: meeting_id.to_string(),
            join_token: join_token.to_string(),
            participant_name: participant_name.to_string(),
            capabilities: None,
            correlation_id: String::new(),
            binding_token: String::new(),
        })),
    };

    let frame = encode_framed(&client_msg);
    send.write_all(&frame).await.expect("write JoinRequest");

    tokio::time::timeout(Duration::from_secs(10), async {
        read_server_message(&mut recv)
            .await
            .expect("read server message")
    })
    .await
    .expect("Timeout waiting for MC response")
}

// ============================================================================
// GC-Level Join Tests (HTTP API)
// ============================================================================

/// Test: Authenticated user can join a meeting via GC and receive a meeting token
/// with MC assignment details.
///
/// Validates the full AC -> GC join flow:
/// 1. Register user via AC (get user JWT)
/// 2. Create meeting via GC (POST /api/v1/meetings)
/// 3. Join meeting via GC (GET /api/v1/meetings/{code})
/// 4. Response contains meeting token (JWT format), correct meeting_id,
///    and mc_assignment with mc_id and grpc_endpoint
#[tokio::test]
async fn test_gc_join_returns_meeting_token_and_mc_assignment() {
    let cluster = cluster().await;
    let (user_token, _) = shared_user(cluster).await;
    let gc_client = GcClient::new(&cluster.gc_base_url);

    // Step 1: Create meeting
    let create_request = CreateMeetingRequest::new("Join Flow Test Meeting");
    let created = gc_client
        .create_meeting(user_token, &create_request)
        .await
        .expect("Should create meeting");

    // Step 2: Join meeting via GC
    let join_response = gc_client
        .join_meeting(&created.meeting_code, user_token)
        .await
        .expect("Should join meeting via GC");

    // Step 4: Verify meeting token is JWT-shaped (three dot-separated base64 segments)
    let token_parts: Vec<&str> = join_response.token.split('.').collect();
    assert_eq!(
        token_parts.len(),
        3,
        "Meeting token should be a JWT (3 dot-separated parts)"
    );
    assert!(
        join_response.token.starts_with("eyJ"),
        "Meeting token should start with base64-encoded JSON header"
    );

    // Step 5: Verify meeting_id matches
    assert_eq!(
        join_response.meeting_id, created.meeting_id,
        "Join response meeting_id should match created meeting"
    );

    // Step 6: Verify MC assignment
    assert!(
        !join_response.mc_assignment.mc_id.is_empty(),
        "MC assignment should have a non-empty mc_id"
    );
    assert!(
        !join_response.mc_assignment.grpc_endpoint.is_empty(),
        "MC assignment should have a non-empty grpc_endpoint"
    );

    // Step 7: Verify expires_in is reasonable (> 0, typical is 900s)
    assert!(
        join_response.expires_in > 0,
        "Meeting token should have a positive expiration"
    );
}

/// Test: Join meeting endpoint rejects unauthenticated requests.
///
/// GET /api/v1/meetings/{code} without Authorization header should return 401.
#[tokio::test]
async fn test_gc_join_rejects_unauthenticated() {
    let cluster = cluster().await;

    let gc_client = GcClient::new(&cluster.gc_base_url);

    let result = gc_client.raw_join_meeting("any-meeting-code", None).await;

    match result {
        Ok(response) => {
            assert_eq!(
                response.status().as_u16(),
                401,
                "Unauthenticated join should return 401"
            );
        }
        Err(e) => {
            panic!("Request should not fail at network level: {}", e);
        }
    }
}

/// Test: Join meeting returns 404 for non-existent meeting code.
///
/// Authenticated user tries to join a meeting code that does not exist.
#[tokio::test]
async fn test_gc_join_returns_404_for_unknown_meeting() {
    let cluster = cluster().await;
    let (user_token, _) = shared_user(cluster).await;
    let gc_client = GcClient::new(&cluster.gc_base_url);

    let result = gc_client
        .raw_join_meeting("nonexistent-meeting-xyz-000", Some(user_token))
        .await;

    match result {
        Ok(response) => {
            assert_eq!(
                response.status().as_u16(),
                404,
                "Non-existent meeting code should return 404"
            );
        }
        Err(e) => {
            panic!("Request should not fail at network level: {}", e);
        }
    }
}

/// Test: Join meeting rejects service tokens (requires user JWT).
///
/// GET /api/v1/meetings/{code} uses `require_user_auth` middleware which
/// rejects non-user tokens. A service token (client_credentials) should
/// receive 401 because the middleware calls `validate_user()` which rejects
/// tokens without a valid user UUID `sub` claim.
#[tokio::test]
async fn test_gc_join_rejects_service_token() {
    let cluster = cluster().await;
    let (user_token, _) = shared_user(cluster).await;

    let auth_client = AuthClient::new(&cluster.ac_base_url);
    let gc_client = GcClient::new(&cluster.gc_base_url);

    // Get a service token (client_credentials flow)
    let token_request =
        TokenRequest::client_credentials("test-client", "test-client-secret-dev-999", "test:all");
    let token_response = auth_client
        .issue_token(token_request)
        .await
        .expect("Should issue service token");

    // Create a meeting with the shared user token so the code exists
    let create_request = CreateMeetingRequest::new("Service Token Test Meeting");
    let created = gc_client
        .create_meeting(user_token, &create_request)
        .await
        .expect("Should create meeting");

    // Try to join with service token — require_user_auth should reject it
    let result = gc_client
        .raw_join_meeting(&created.meeting_code, Some(&token_response.access_token))
        .await
        .expect("Network request should succeed");

    let status = result.status().as_u16();

    assert_eq!(
        status, 401,
        "Service token should be rejected by require_user_auth middleware"
    );
}

/// Test: Guest token join succeeds when allow_guests is enabled.
///
/// Creates a meeting with allow_guests=true, then requests a guest token.
/// The guest-token endpoint is public (no auth required).
#[tokio::test]
async fn test_gc_guest_join_succeeds_when_allowed() {
    let cluster = cluster().await;
    let (user_token, _) = shared_user(cluster).await;
    let gc_client = GcClient::new(&cluster.gc_base_url);

    // Create meeting with allow_guests enabled
    let mut create_request = CreateMeetingRequest::new("Guest Allowed Meeting");
    create_request.allow_guests = Some(true);
    create_request.waiting_room_enabled = Some(false);

    let created = gc_client
        .create_meeting(user_token, &create_request)
        .await
        .expect("Should create meeting with allow_guests=true");

    // Request guest token (public endpoint, no auth)
    let guest_request = env_tests::fixtures::gc_client::GuestTokenRequest {
        display_name: "Test Guest".to_string(),
        captcha_token: "test-captcha-token".to_string(),
    };

    let result = gc_client
        .get_guest_token(&created.meeting_code, &guest_request)
        .await;

    let join_response = result.expect("Guest join should succeed when allow_guests=true");

    assert!(
        !join_response.token.is_empty(),
        "Guest should receive a meeting token"
    );
    assert_eq!(
        join_response.meeting_id, created.meeting_id,
        "Guest token should be for the correct meeting"
    );
}

/// Test: Guest token join is rejected when allow_guests is disabled.
///
/// Creates a meeting with default settings (allow_guests=false), then
/// attempts to get a guest token. Should be rejected.
#[tokio::test]
async fn test_gc_guest_join_rejected_when_disabled() {
    let cluster = cluster().await;
    let (user_token, _) = shared_user(cluster).await;
    let gc_client = GcClient::new(&cluster.gc_base_url);

    // Create meeting with default settings (allow_guests=false)
    let create_request = CreateMeetingRequest::new("Guest Denied Meeting");

    let created = gc_client
        .create_meeting(user_token, &create_request)
        .await
        .expect("Should create meeting with default settings");

    // Request guest token — should be rejected
    let guest_request = env_tests::fixtures::gc_client::GuestTokenRequest {
        display_name: "Rejected Guest".to_string(),
        captcha_token: "test-captcha-token".to_string(),
    };

    let result = gc_client
        .get_guest_token(&created.meeting_code, &guest_request)
        .await;

    match result {
        Ok(_) => {
            panic!("Guest token should NOT succeed when allow_guests is false");
        }
        Err(GcClientError::RequestFailed { status, .. }) => {
            // GC validates inputs first, then checks allow_guests → 403 Forbidden
            assert_eq!(
                status, 403,
                "Expected 403 Forbidden (guests disabled), got {}",
                status
            );
        }
        Err(e) => {
            panic!("Unexpected error: {}", e);
        }
    }
}

// ============================================================================
// MC WebTransport Tests (full cross-service flow)
// ============================================================================

/// Test: Full cross-service join flow through to MC WebTransport.
///
/// Validates:
/// 1. GC issues a meeting token that MC accepts
/// 2. MC WebTransport connection succeeds with dev certs
/// 3. Protobuf JoinRequest is processed correctly
/// 4. JoinResponse contains participant_id and correlation_id (ADR-0023)
#[tokio::test]
async fn test_mc_webtransport_connect_and_join() {
    let cluster = cluster().await;

    let auth_client = AuthClient::new(&cluster.ac_base_url);
    let gc_client = GcClient::new(&cluster.gc_base_url);

    // Step 1: Register user, create meeting, join via GC
    let (user_token, display_name) =
        register_test_user(&auth_client, "WebTransport Join User").await;

    let create_request = CreateMeetingRequest::new("WebTransport Test Meeting");
    let created = gc_client
        .create_meeting(&user_token, &create_request)
        .await
        .expect("Should create meeting");

    let gc_join = gc_client
        .join_meeting(&created.meeting_code, &user_token)
        .await
        .expect("Should join meeting via GC");

    // Step 2: Connect to MC via WebTransport
    let conn = connect_mc(cluster.mc_webtransport_url()).await;

    // Step 3: Send JoinRequest with the meeting token from GC
    let response = send_join_and_read_response(
        &conn,
        &gc_join.meeting_id.to_string(),
        &gc_join.token,
        &display_name,
    )
    .await;

    // Step 4: Verify JoinResponse
    match &response.message {
        Some(server_message::Message::JoinResponse(join)) => {
            assert!(
                !join.participant_id.is_empty(),
                "JoinResponse should contain a non-empty participant_id"
            );
            assert!(
                !join.correlation_id.is_empty(),
                "JoinResponse should contain a non-empty correlation_id (ADR-0023)"
            );
            assert!(
                !join.binding_token.is_empty(),
                "JoinResponse should contain a non-empty binding_token (ADR-0023)"
            );
        }
        Some(server_message::Message::Error(e)) => {
            panic!(
                "MC returned error instead of JoinResponse: code={}, message={}",
                e.code, e.message
            );
        }
        other => {
            panic!("Expected JoinResponse from MC, got {:?}", other);
        }
    }
}

/// Test: MC rejects a JoinRequest with an invalid meeting token.
///
/// Validates defense-in-depth: MC independently validates JWTs via AC's JWKS,
/// rejecting tokens that are not properly signed. Uses a structurally valid
/// but fake JWT (valid base64 header/payload, garbage signature) to exercise
/// the signature verification path rather than just the malformed-token check.
#[tokio::test]
async fn test_mc_rejects_invalid_meeting_token() {
    let cluster = cluster().await;

    // Connect to MC directly — no need for GC join since we're testing rejection
    let conn = connect_mc(cluster.mc_webtransport_url()).await;

    // Structurally valid JWT with garbage signature.
    // Header: {"alg":"EdDSA","typ":"JWT"}
    // Payload: {"sub":"attacker","meeting_id":"fake","exp":9999999999}
    // Signature: invalid
    let fake_token = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.\
        eyJzdWIiOiJhdHRhY2tlciIsIm1lZXRpbmdfaWQiOiJmYWtlIiwiZXhwIjo5OTk5OTk5OTk5fQ.\
        invalid_signature_that_will_not_verify";

    let response =
        send_join_and_read_response(&conn, "fake-meeting-id", fake_token, "Attacker").await;

    // MC should return an error with Unauthorized code
    match &response.message {
        Some(server_message::Message::Error(e)) => {
            assert_eq!(
                e.code,
                proto_gen::signaling::ErrorCode::Unauthorized as i32,
                "MC should reject invalid token with Unauthorized, got code: {}",
                e.code
            );
            // Security: error message should be generic, not reveal validation details
            assert!(
                !e.message.contains("signature")
                    && !e.message.contains("JWKS")
                    && !e.message.contains("key"),
                "Error message should not reveal validation internals: {}",
                e.message
            );
        }
        Some(server_message::Message::JoinResponse(_)) => {
            panic!("MC should NOT accept a fake token — JoinResponse returned for invalid JWT");
        }
        other => {
            panic!(
                "Expected Error(Unauthorized) from MC for invalid token, got {:?}",
                other
            );
        }
    }
}

/// Test: When a second participant joins, the first receives a ParticipantJoined
/// notification via the signaling bridge.
///
/// Validates:
/// 1. Two independent users can join the same meeting through the full flow
/// 2. MC's signaling bridge delivers ParticipantJoined to existing participants
/// 3. The notification contains the new participant's information
#[tokio::test]
async fn test_second_participant_receives_join_notification() {
    let cluster = cluster().await;

    let auth_client = AuthClient::new(&cluster.ac_base_url);
    let gc_client = GcClient::new(&cluster.gc_base_url);

    // Step 1: Register two users
    let (user1_token, user1_name) = register_test_user(&auth_client, "Bridge Test User 1").await;
    let (user2_token, user2_name) = register_test_user(&auth_client, "Bridge Test User 2").await;

    // Step 2: User 1 creates a meeting
    let create_request = CreateMeetingRequest::new("Bridge Notification Test");
    let created = gc_client
        .create_meeting(&user1_token, &create_request)
        .await
        .expect("Should create meeting");

    let meeting_id_str = created.meeting_id.to_string();

    // Step 3: Both users join via GC to get meeting tokens
    let gc_join1 = gc_client
        .join_meeting(&created.meeting_code, &user1_token)
        .await
        .expect("User 1 should join meeting via GC");

    let gc_join2 = gc_client
        .join_meeting(&created.meeting_code, &user2_token)
        .await
        .expect("User 2 should join meeting via GC");

    // Step 4: User 1 connects to MC and joins
    let conn1 = connect_mc(cluster.mc_webtransport_url()).await;
    let (mut send1, mut recv1) = conn1
        .open_bi()
        .await
        .expect("open bi stream for user 1")
        .await
        .expect("bi stream 1 ready");

    let join_msg1 = ClientMessage {
        message: Some(client_message::Message::JoinRequest(JoinRequest {
            meeting_id: meeting_id_str.clone(),
            join_token: gc_join1.token,
            participant_name: user1_name,
            capabilities: None,
            correlation_id: String::new(),
            binding_token: String::new(),
        })),
    };
    send1
        .write_all(&encode_framed(&join_msg1))
        .await
        .expect("write JoinRequest for user 1");

    // Read JoinResponse for user 1
    let response1 = tokio::time::timeout(Duration::from_secs(10), async {
        read_server_message(&mut recv1)
            .await
            .expect("read JoinResponse for user 1")
    })
    .await
    .expect("Timeout waiting for user 1 JoinResponse");

    assert!(
        matches!(
            &response1.message,
            Some(server_message::Message::JoinResponse(_))
        ),
        "User 1 should receive JoinResponse, got {:?}",
        response1.message
    );

    // Step 5: User 2 connects to MC and joins
    let conn2 = connect_mc(cluster.mc_webtransport_url()).await;
    let response2 =
        send_join_and_read_response(&conn2, &meeting_id_str, &gc_join2.token, &user2_name).await;

    assert!(
        matches!(
            &response2.message,
            Some(server_message::Message::JoinResponse(_))
        ),
        "User 2 should receive JoinResponse, got {:?}",
        response2.message
    );

    // Step 6: User 1 should receive ParticipantJoined notification via bridge
    let notification = tokio::time::timeout(Duration::from_secs(10), async {
        read_server_message(&mut recv1)
            .await
            .expect("read ParticipantJoined notification")
    })
    .await
    .expect("Timeout: User 1 did not receive ParticipantJoined notification after User 2 joined");

    match &notification.message {
        Some(server_message::Message::ParticipantJoined(joined)) => {
            let participant = joined
                .participant
                .as_ref()
                .expect("ParticipantJoined should contain participant info");
            assert!(
                !participant.participant_id.is_empty(),
                "ParticipantJoined notification should have non-empty participant_id"
            );
        }
        other => {
            panic!(
                "Expected ParticipantJoined notification for user 1, got {:?}",
                other
            );
        }
    }
}
