//! Env-test: MH meeting teardown on the live Kind cluster (story 2 task 11;
//! R-20, R-21; ADR-0036 §8, §11).
//!
//! # What this proves that nothing else can
//!
//! That a LONG-RUNNING handler pod, after a meeting ends, admits a meeting
//! exactly as a fresh pod would — and that the operator-visible signals say so:
//! the registered-meetings gauge FALLS, the edges return, and the teardown
//! counter increments; plus the ownership-reject arm. The integration tier
//! (`crates/mh-service/tests/end_meeting_integration.rs`) proves the same
//! decisions in-process; only a live pod proves them on the deployed image, the
//! deployed ConfigMap and the real scrape path.
//!
//! # How it reaches MH
//!
//! Directly, as the meeting-controller service principal: Layer 7
//! (`scripts/layer7.sh`, step (i)) forwards each MH POD's gRPC port and exports
//! `ENV_TEST_MH_{0,1}_GRPC_URL` plus `ENV_TEST_MH_{0,1}_POD_IP`. MC does not call
//! `EndMeeting` until story 2 task 12, and a mismatched `mc_id` is unreachable
//! through MC at all (MC always sends its own), so both arms need a direct call.
//! The token comes from AC's client-credentials endpoint for the Kind dev
//! `meeting-controller` client — never minted locally — narrowed to
//! `service.write.mh`. It is used only against MH and never printed.
//! The MH client is generated by `proto-gen` (a wire-contract crate): ADR-0028's
//! layering is unchanged; only the credential convention is.
//!
//! # Containment — this test must never touch a meeting it does not own
//!
//! Every meeting id is a fresh uuid, which is the containing key (the ownership
//! state is keyed on `meeting_id`). Every registration is generation 1: a high
//! generation cannot be taken back within a process, so a large value would
//! wedge that id on that pod for the cluster's lifetime. Cleanup is STRUCTURAL —
//! a `Drop` guard releases everything this test registered, so a mid-test panic
//! cannot leak a registration (and its edges) into every later suite on the
//! cluster. `mc_grpc_endpoint` is a never-dialled placeholder: MH dials it only
//! for WebTransport clients of the meeting, and none joins a test meeting.
//!
//! # Reading metrics: pinned, relative, confirmed, no wall clock
//!
//! Metrics are read through Prometheus — the suite's one metrics path — pinned
//! to the `instance` of the pod the test CALLED (resolved by Layer 7 from the
//! same lookup that feeds the forward), never "any instance". Every expectation
//! is a DELTA from that pod's own baseline, because other suites share the pods.
//! Prometheus samples on an interval, so every read is a bounded poll until a
//! condition, never a sleep-then-assert — and the gauge FALL is asserted only
//! against a peak this test has already OBSERVED, because "below baseline" is
//! trivially true of a registration that was never scraped. Each wait fails
//! with its own phase token (PRECONDITION / RISE-NOT-OBSERVED / REJECT-COUNT /
//! RELEASE-COUNT / FALL-NOT-OBSERVED / EDGES-NOT-RETURNED / UNKNOWN-COUNT /
//! LIMITS), so a slow scrape never reads as a reclamation bug.
//!
//! What stays SYNCHRONOUS, read off the gRPC response and never re-expressed as
//! a lagged metric: the reject's status code, the acknowledgements, and
//! `applied_generation == 1` on the re-registration.

#![cfg(feature = "flows")]

use std::sync::{Arc, Mutex};
use std::time::Duration;

use env_tests::cluster::ClusterConnection;
use env_tests::fixtures::auth_client::TokenRequest;
use env_tests::fixtures::kube::{configmap_u64, deployment_env_value, secret_key};
use env_tests::fixtures::metrics::{gauge_by_instance_present, poll_until_pinned_instance};
use env_tests::fixtures::{AuthClient, PrometheusClient};
use proto_gen::dark_tower::internal::v1::media_handler_service_client::MediaHandlerServiceClient;
use proto_gen::dark_tower::internal::v1::{
    CandidateSource, EgressStream, EndMeetingRequest, RegisterMeetingRequest, SubscriberSlot,
};
use proto_gen::dark_tower::signaling::v1::TransportMode;
use tonic::metadata::MetadataValue;
use tonic::transport::{Channel, Endpoint};
use tonic::{Code, Request};

/// Where MC's own AC client credentials are deployed. The test READS them from
/// the cluster rather than restating them: the Secret is the single source (it
/// matches what `infra/kind/scripts/setup.sh` seeds into AC), and a copy here
/// would drift on rotation and then fail as an apparent environment fault.
const MC_DEPLOYMENT: &str = "mc-0";
const MC_CLIENT_ID_ENV: &str = "MC_CLIENT_ID";
const MC_SECRET: &str = "mc-service-secrets";
const MC_SECRET_KEY: &str = "MC_CLIENT_SECRET";
/// Narrowed to the one scope MH's gate needs; the dev client also holds
/// `service.write.gc`, which this test has no use for.
const MC_SCOPE: &str = "service.write.mh";

/// Never dialled (see the module docs). Syntactically valid so it passes MH's
/// scheme check; `.invalid` is reserved, so it cannot resolve by accident.
const NEVER_DIALLED_MC_ENDPOINT: &str = "http://env-test-mc.invalid:50052";

/// Scrape-convergence bound for one metric wait (same bound as test 28).
const METRIC_BOUND: Duration = Duration::from_secs(120);
const POLL_INTERVAL: Duration = Duration::from_secs(2);

const REGISTERED: &str = "max by (instance) (mh_media_registered_meetings)";
const EDGES: &str = "max by (instance) (mh_media_egress_edges)";

fn teardowns(outcome: &str) -> String {
    format!("sum by (instance) (mh_media_meeting_teardowns_total{{outcome=\"{outcome}\"}})")
}

/// Read a Layer-7-exported variable, never skipping.
fn required_env(key: &str) -> String {
    std::env::var(key).unwrap_or_else(|_| {
        panic!(
            "PRECONDITION: {key} is unset. Layer 7 (scripts/layer7.sh, step (i)) starts the \
             per-pod MH gRPC port-forwards and exports it; run this suite through Layer 7. \
             This test is never skipped."
        )
    })
}

struct Handler {
    name: String,
    grpc_url: String,
    pod_ip: String,
}

fn handlers() -> Vec<Handler> {
    (0..2)
        .map(|n| Handler {
            name: format!("mh-{n}"),
            grpc_url: required_env(&format!("ENV_TEST_MH_{n}_GRPC_URL")),
            pod_ip: required_env(&format!("ENV_TEST_MH_{n}_POD_IP")),
        })
        .collect()
}

/// Two egress edges: two participants each hearing the other.
fn two_edges() -> Vec<EgressStream> {
    [(1_u32, 1_u32, 2_u32), (2, 2, 1)]
        .into_iter()
        .map(|(egress_stream_id, subscriber, candidate)| EgressStream {
            egress_stream_id,
            subscriber: Some(SubscriberSlot {
                sender_id: subscriber,
                slot_id: 0,
            }),
            candidate_sources: vec![CandidateSource {
                sender_id: candidate,
                stream_number: 0,
            }],
            priority_group: 0,
            supersede_on_independent_frame: false,
            transport_mode: TransportMode::Datagram as i32,
        })
        .collect()
}
const TWO_EDGES: f64 = 2.0;

fn authed<T>(token: &str, message: T) -> Request<T> {
    let mut request = Request::new(message);
    let value: MetadataValue<_> = format!("Bearer {token}")
        .parse()
        .expect("a bearer header parses");
    request.metadata_mut().insert("authorization", value);
    request
}

async fn connect(handler: &Handler) -> MediaHandlerServiceClient<Channel> {
    let channel = Endpoint::from_shared(handler.grpc_url.clone())
        .expect("the exported URL parses")
        .connect_timeout(Duration::from_secs(5))
        .timeout(Duration::from_secs(10))
        .connect()
        .await
        .unwrap_or_else(|e| {
            panic!(
                "PRECONDITION: cannot connect to {}'s gRPC at {} ({e}) — the Layer-7 \
                 port-forward is down (a forward dies with its pod)",
                handler.name, handler.grpc_url
            )
        });
    MediaHandlerServiceClient::new(channel)
}

// ---------------------------------------------------------------------------
// Structural cleanup
// ---------------------------------------------------------------------------

/// A meeting this test registered: where, and under which `mc_id`.
struct Owned {
    grpc_url: String,
    meeting_id: String,
    mc_id: String,
}

/// Releases every meeting still recorded here when dropped — on success AND on
/// a panic mid-test. Recorded BEFORE each registration call, so even a
/// registration whose response was lost is released. `Drop` cannot be async,
/// so it drives the releases on a fresh thread with its own runtime.
struct ReleaseOnDrop {
    token: String,
    owned: Arc<Mutex<Vec<Owned>>>,
}

impl ReleaseOnDrop {
    fn record(&self, grpc_url: &str, meeting_id: &str, mc_id: &str) {
        self.owned.lock().expect("cleanup registry").push(Owned {
            grpc_url: grpc_url.to_string(),
            meeting_id: meeting_id.to_string(),
            mc_id: mc_id.to_string(),
        });
    }

    /// The test released it itself; nothing left to clean up.
    fn forget(&self, meeting_id: &str) {
        self.owned
            .lock()
            .expect("cleanup registry")
            .retain(|o| o.meeting_id != meeting_id);
    }
}

impl Drop for ReleaseOnDrop {
    fn drop(&mut self) {
        let owned: Vec<Owned> =
            std::mem::take(&mut *self.owned.lock().unwrap_or_else(|p| p.into_inner()));
        if owned.is_empty() {
            return;
        }
        let token = self.token.clone();
        let released = std::thread::spawn(move || {
            let runtime = tokio::runtime::Builder::new_current_thread()
                .enable_all()
                .build()
                .expect("cleanup runtime");
            runtime.block_on(async move {
                for o in owned {
                    let result = async {
                        let channel = Endpoint::from_shared(o.grpc_url.clone())
                            .map_err(|e| e.to_string())?
                            .connect_timeout(Duration::from_secs(5))
                            .timeout(Duration::from_secs(10))
                            .connect()
                            .await
                            .map_err(|e| e.to_string())?;
                        MediaHandlerServiceClient::new(channel)
                            .end_meeting(authed(
                                &token,
                                EndMeetingRequest {
                                    meeting_id: o.meeting_id.clone(),
                                    mc_id: o.mc_id.clone(),
                                },
                            ))
                            .await
                            .map_err(|s| format!("{:?}: {}", s.code(), s.message()))
                    }
                    .await;
                    // Loud, but never a panic inside Drop (it would abort a test
                    // that is already unwinding). The token is never printed.
                    if let Err(e) = result {
                        eprintln!(
                            "CLEANUP: could not release test meeting {} at {}: {e} — it holds \
                             a registration and its edges until that pod restarts",
                            o.meeting_id, o.grpc_url
                        );
                    }
                }
            });
        })
        .join();
        if released.is_err() {
            eprintln!("CLEANUP: the release thread panicked; test meetings may be leaked");
        }
    }
}

// ---------------------------------------------------------------------------
// The test
// ---------------------------------------------------------------------------

#[tokio::test]
async fn a_long_running_mh_pod_releases_an_ended_meeting_and_admits_like_a_fresh_one() {
    let cluster = ClusterConnection::new()
        .await
        .expect("PRECONDITION: cluster connection (ENV_TEST_* URLs)");
    let prom = PrometheusClient::new(&cluster.prometheus_base_url);
    let handlers = handlers();

    // PRECONDITION — the AC-issued meeting-controller token, never minted here,
    // from the credentials MC itself is deployed with. A refusal names the
    // CREDENTIAL, so a rotation mismatch is not triaged as a broken forward.
    let client_id = deployment_env_value(MC_DEPLOYMENT, MC_CLIENT_ID_ENV);
    let client_secret = secret_key(MC_SECRET, MC_SECRET_KEY);
    let token = AuthClient::new(&cluster.ac_base_url)
        .issue_token(TokenRequest::client_credentials(
            &client_id,
            client_secret,
            MC_SCOPE,
        ))
        .await
        .unwrap_or_else(|e| {
            panic!(
                "PRECONDITION: AC refused MC's deployed client credentials ({client_id}, secret \
                 from {MC_SECRET}/{MC_SECRET_KEY}) — a CREDENTIAL fault: the deployed Secret and \
                 what AC was seeded with disagree. Not a forward or teardown fault. {e}"
            )
        })
        .access_token;
    let cleanup = ReleaseOnDrop {
        token: token.clone(),
        owned: Arc::new(Mutex::new(Vec::new())),
    };

    // LIMITS — both resource-guard limits are published from the value
    // enforcement reads, i.e. equal the DEPLOYED ConfigMap (never a literal here).
    let edge_limit = configmap_u64("mh-service-config", "MH_MAX_TOTAL_EGRESS_EDGES");
    let meeting_limit = configmap_u64("mh-service-config", "MH_MAX_REGISTERED_MEETINGS");
    for (metric, deployed) in [
        ("mh_media_egress_edges_limit", edge_limit),
        ("mh_media_registered_meetings_limit", meeting_limit),
    ] {
        gauge_by_instance_present(&prom, metric, handlers.len(), METRIC_BOUND).await;
        for handler in &handlers {
            #[allow(clippy::cast_precision_loss)]
            let expected = deployed as f64;
            poll_until_pinned_instance(
                &prom,
                &format!("max by (instance) ({metric})"),
                &handler.pod_ip,
                METRIC_BOUND,
                POLL_INTERVAL,
                "LIMITS",
                &format!("{expected} (the deployed ConfigMap value)"),
                |v| (v - expected).abs() < f64::EPSILON,
            )
            .await;
        }
    }

    for handler in &handlers {
        exercise_one_handler(&prom, &cleanup, &token, handler).await;
    }
}

/// The whole lifecycle on ONE pod: register, reject a foreign release, release,
/// no-op on repeat, then admit the same id afresh.
async fn exercise_one_handler(
    prom: &PrometheusClient,
    cleanup: &ReleaseOnDrop,
    token: &str,
    handler: &Handler,
) {
    let run = uuid::Uuid::new_v4().simple().to_string();
    let meeting_id = format!("env-test-teardown-{run}");
    let owner_mc = format!("env-test-mc-{run}");
    let intruder_mc = format!("env-test-intruder-{run}");
    let pinned = |promql: String,
                  phase: &'static str,
                  expectation: String,
                  pred: Box<dyn Fn(f64) -> bool + Send>| {
        let pod_ip = handler.pod_ip.clone();
        async move {
            poll_until_pinned_instance(
                prom,
                &promql,
                &pod_ip,
                METRIC_BOUND,
                POLL_INTERVAL,
                phase,
                &expectation,
                pred,
            )
            .await
        }
    };
    let name = &handler.name;
    let mut client = connect(handler).await;

    // Baselines for THIS pod. Each is also a presence control: every series here
    // is published at 0 from process start, so ABSENT is a failure, not zero.
    let any = |_: f64| true;
    let base_registered = pinned(
        REGISTERED.into(),
        "PRECONDITION",
        "presence".into(),
        Box::new(any),
    )
    .await;
    let base_edges = pinned(
        EDGES.into(),
        "PRECONDITION",
        "presence".into(),
        Box::new(any),
    )
    .await;
    let base_rejected = pinned(
        teardowns("rejected_ownership"),
        "PRECONDITION",
        "presence".into(),
        Box::new(any),
    )
    .await;
    let base_released = pinned(
        teardowns("released"),
        "PRECONDITION",
        "presence".into(),
        Box::new(any),
    )
    .await;
    let base_unknown = pinned(
        teardowns("unknown_meeting"),
        "PRECONDITION",
        "presence".into(),
        Box::new(any),
    )
    .await;

    // 1. Register (generation 1, two edges). The auth positive control: a
    //    refusal here is the token or the forward, never teardown logic.
    cleanup.record(&handler.grpc_url, &meeting_id, &owner_mc);
    let registered = client
        .register_meeting(authed(token, register(&meeting_id, &owner_mc)))
        .await
        .unwrap_or_else(|s| {
            panic!(
                "PRECONDITION: {name} refused the first RegisterMeeting ({:?}: {}) — the \
                 token or the forward, not teardown",
                s.code(),
                s.message()
            )
        })
        .into_inner();
    assert_eq!(
        registered.applied_generation, 1,
        "PRECONDITION: {name} did not install the test meeting's generation-1 policy"
    );

    // 2. CONFIRM THE RISE on this pod before anything is released — the positive
    //    control the fall is measured against.
    let peak_registered = pinned(
        REGISTERED.into(),
        "RISE-NOT-OBSERVED",
        format!(
            ">= {} (baseline {base_registered} + this meeting)",
            base_registered + 1.0
        ),
        Box::new(move |v| v >= base_registered + 1.0),
    )
    .await;
    let peak_edges = pinned(
        EDGES.into(),
        "RISE-NOT-OBSERVED",
        format!(
            ">= {} (baseline {base_edges} + two edges)",
            base_edges + TWO_EDGES
        ),
        Box::new(move |v| v >= base_edges + TWO_EDGES),
    )
    .await;

    // 3. A DIFFERENT mc_id: FAILED_PRECONDITION (never PERMISSION_DENIED, never an
    //    acknowledgement), counted, and nothing released.
    let rejected = client
        .end_meeting(authed(
            token,
            EndMeetingRequest {
                meeting_id: meeting_id.clone(),
                mc_id: intruder_mc,
            },
        ))
        .await
        .expect_err("REJECT: a mismatched mc_id must be an error status, never an acknowledgement");
    assert_eq!(
        rejected.code(),
        Code::FailedPrecondition,
        "REJECT on {name}"
    );
    assert_ne!(rejected.code(), Code::PermissionDenied, "REJECT on {name}");
    assert!(
        !rejected.message().contains(&owner_mc),
        "REJECT on {name}: the status must not disclose the registering mc_id"
    );
    pinned(
        teardowns("rejected_ownership"),
        "REJECT-COUNT",
        format!(">= {}", base_rejected + 1.0),
        Box::new(move |v| v >= base_rejected + 1.0),
    )
    .await;
    // Read AFTER the reject was scraped, so this scrape post-dates it: the
    // meeting must still be held.
    pinned(
        REGISTERED.into(),
        "REJECT-RELEASED-SOMETHING",
        format!(">= {peak_registered} (unchanged by the rejected release)"),
        Box::new(move |v| v >= peak_registered),
    )
    .await;

    // 4. The registering MC releases: acknowledged, counted, and the gauge FALLS
    //    below the peak this test observed, with the edges returned.
    let released = client
        .end_meeting(authed(
            token,
            EndMeetingRequest {
                meeting_id: meeting_id.clone(),
                mc_id: owner_mc.clone(),
            },
        ))
        .await
        .unwrap_or_else(|s| panic!("RELEASE on {name}: {:?}: {}", s.code(), s.message()))
        .into_inner();
    assert!(released.acknowledged, "RELEASE on {name}: not acknowledged");
    cleanup.forget(&meeting_id);
    pinned(
        teardowns("released"),
        "RELEASE-COUNT",
        format!(">= {}", base_released + 1.0),
        Box::new(move |v| v >= base_released + 1.0),
    )
    .await;
    pinned(
        REGISTERED.into(),
        "FALL-NOT-OBSERVED",
        format!(
            "<= {} (the observed peak {peak_registered} minus this meeting)",
            peak_registered - 1.0
        ),
        Box::new(move |v| v <= peak_registered - 1.0),
    )
    .await;
    pinned(
        EDGES.into(),
        "EDGES-NOT-RETURNED",
        format!(
            "<= {} (the observed peak {peak_edges} minus two edges)",
            peak_edges - TWO_EDGES
        ),
        Box::new(move |v| v <= peak_edges - TWO_EDGES),
    )
    .await;

    // 5. Releasing again: an acknowledged no-op, counted as unknown_meeting.
    let repeat = client
        .end_meeting(authed(
            token,
            EndMeetingRequest {
                meeting_id: meeting_id.clone(),
                mc_id: owner_mc.clone(),
            },
        ))
        .await
        .unwrap_or_else(|s| panic!("UNKNOWN on {name}: {:?}: {}", s.code(), s.message()))
        .into_inner();
    assert!(
        repeat.acknowledged,
        "UNKNOWN on {name}: a released meeting must acknowledge"
    );
    pinned(
        teardowns("unknown_meeting"),
        "UNKNOWN-COUNT",
        format!(">= {}", base_unknown + 1.0),
        Box::new(move |v| v >= base_unknown + 1.0),
    )
    .await;

    // 6. THE FRESH-POD PROOF: the same id at generation 1 installs, exactly as
    //    on a pod that never saw it. Were the generation remembered, this would
    //    be refused as stale and echo the old generation instead.
    cleanup.record(&handler.grpc_url, &meeting_id, &owner_mc);
    let again = client
        .register_meeting(authed(token, register(&meeting_id, &owner_mc)))
        .await
        .unwrap_or_else(|s| panic!("FRESH-INSTALL on {name}: {:?}: {}", s.code(), s.message()))
        .into_inner();
    assert_eq!(
        again.applied_generation, 1,
        "FRESH-INSTALL on {name}: a released meeting re-created at generation 1 must install \
         as on a fresh pod"
    );
    let done = client
        .end_meeting(authed(
            token,
            EndMeetingRequest {
                meeting_id: meeting_id.clone(),
                mc_id: owner_mc,
            },
        ))
        .await
        .unwrap_or_else(|s| panic!("CLEANUP on {name}: {:?}: {}", s.code(), s.message()))
        .into_inner();
    assert!(done.acknowledged, "CLEANUP on {name}");
    cleanup.forget(&meeting_id);
}

fn register(meeting_id: &str, mc_id: &str) -> RegisterMeetingRequest {
    RegisterMeetingRequest {
        meeting_id: meeting_id.to_string(),
        mc_id: mc_id.to_string(),
        mc_grpc_endpoint: NEVER_DIALLED_MC_ENDPOINT.to_string(),
        egress_streams: two_edges(),
        selection_rules: None,
        // Generation 1 ONLY — see "Containment" in the module docs.
        policy_generation: 1,
        server_muted_sources: Vec::new(),
    }
}
