//! # NOT PRODUCTION CODE — read this before changing or deleting anything here
//!
//! This crate is a **deliberately non-production** reference implementation of
//! the ADR-0036 media-frame cryptography, used **only** to generate
//! `proto/test-vectors/frame-v2.vectors.json`. Nothing in any service links it,
//! and nothing ever should.
//!
//! ## Why dead-looking Rust crypto exists here on purpose
//!
//! **No production Rust component seals, signs, verifies or decrypts a media
//! frame.** A media handler is keyless (ADR-0036 §4, §7) and a meeting
//! controller never encrypts. All of it is TypeScript. So story 1 and story 2
//! encrypt *and* decrypt in the same TypeScript, and a **self-consistent**
//! TypeScript crypto error passes every acceptance criterion in the story and
//! survives until a non-TypeScript implementation appears.
//!
//! This crate is that implementation. It is the **only** independent check on
//! the TypeScript crypto, which is why it must not be deleted as dead code in a
//! later cleanup. That is enforced mechanically, not by this comment:
//! `scripts/guards/simple/validate-frame-vectors.sh` check **g11** fails if this
//! crate is missing or absent from the workspace `members` list, so deleting it
//! reds Layer 3 rather than reading as a clean dead-code removal.
//!
//! ## Its irreplaceable job is exactly three computations
//!
//! [`spec`] holds them, and nothing else in the tree checks them:
//!
//! 1. **The AEAD associated-data span** — the publisher region alone.
//! 2. **The signed range** — publisher region ‖ payload, deliberately a strict
//!    superset of the associated data.
//! 3. **The detached-tag split** — `key_id(8) || tag(16) || ciphertext(n)`.
//!
//! All three are computed **from the ADR-0036 specification text**, never by
//! mirroring the TypeScript codec. Mirroring would make the vectors validate a
//! shared error instead of catching it. They are then cross-asserted against
//! `media-protocol`'s parser-walk-derived ranges, giving three independent
//! derivations pinned to one value.
//!
//! ## What is NOT authored here
//!
//! The `SFrame` key schedule and the AEAD primitive are **anchored externally**
//! to the sframe-wg test vectors at commit `025d568`, vendored under
//! `proto/test-vectors/external/sframe-wg/` with provenance recorded. See
//! [`schedule`] and `tests/external_sframe_gate.rs`. That is a distinct
//! no-correlated-error gate: independent authorship of a key schedule would be
//! worth far less than agreement with the specification's own vectors.
//!
//! Framing is **not** re-implemented either: [`rows`] calls
//! `media_protocol::codec::encode_frame`. Framing is not one of the three
//! protected computations, and a second Rust frame encoder would be duplication
//! with no compensating value.
//!
//! ## Determinism is a requirement, not a nicety
//!
//! No `rand`, no `getrandom`, no clock. Every key is a fixed synthetic fixture
//! ([`fixtures`]) and `Ed25519` is deterministic per RFC 8032, so regenerating
//! with nothing changed leaves `git diff` empty. A churny generator makes the
//! drift guard useless within two stories.

#![warn(clippy::pedantic)]
// Same rationale as `media-protocol`: any field packed into a narrower wire
// width must use a checked conversion sized to the field. On the key-id path a
// masking cast aliases sender 65536 to 0 — a key-id collision, therefore
// (key, nonce) reuse, therefore authentication-key recovery under AES-GCM.
#![deny(
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss
)]
#![forbid(unsafe_code)]

pub mod crypto;
pub mod error;
pub mod fixtures;
pub mod json;
pub mod kid;
pub mod mutate;
pub mod rows;
pub mod schedule;
pub mod spec;

/// Emitted verbatim into the generated JSON as `_non_production`.
///
/// Removing the label from this crate reds guard check **g1**, which asserts the
/// key is present and non-empty in the generated file. The label is therefore
/// load-bearing rather than decorative.
pub const NON_PRODUCTION_BANNER: &str = concat!(
    "GENERATED BY crates/media-vector-gen, WHICH IS DELIBERATELY NON-PRODUCTION. ",
    "No production Rust component seals, signs, verifies or decrypts a media frame ",
    "(ADR-0036 §4/§7: MH is keyless, MC never encrypts), so that generator is the only ",
    "independent check on the TypeScript crypto. Do not delete it as dead Rust crypto: ",
    "guard check g11 fails if the crate is missing or not a workspace member. ",
    "Every key in this file is a synthetic low-entropy fixture, never CSPRNG output, ",
    "and nothing here derives from any real environment or secret."
);

/// The `SFrame` ciphersuite this wire format uses: `AES_256_GCM_SHA512_128`,
/// RFC 9605 §8.1. Forces HKDF-SHA512 throughout, hence a 64-byte PRK.
pub const CIPHER_SUITE_ID: u16 = 0x0005;
/// Human-readable ciphersuite name, pinned cross-language.
pub const CIPHER_SUITE_NAME: &str = "AES_256_GCM_SHA512_128";
/// Schema version of the emitted vector file.
pub const SCHEMA_VERSION: u32 = 1;

/// Where the generated file lives, relative to the workspace root.
pub const VECTOR_FILE_PATH: &str = "proto/test-vectors/frame-v2.vectors.json";

/// Assemble the complete vector file.
///
/// # Errors
///
/// Propagates any [`error::GenError`] from row construction.
pub fn build_vector_file() -> Result<json::VectorFile, error::GenError> {
    inventory::build()
}

pub mod inventory;
